POST http://localhost:8000/add_task
Content-Type: application/json

{
   "title":"testing",
    "description":"testing second",
    "status":"pending"

    }

###
GET http://localhost:8000/all_tasks
Content-Type: application/json 

###
POST  http://localhost:8000/update_task
Content-Type: application/json

{
    "_id":"698623d19f6a96db77ab28cb",
   "title":"testing",
    "description":"testing update",
    "status":"pending"

    }

###
DELETE  http://localhost:8000/delete_task
Content-Type: application/json

{
    "_id":"698623d19f6a96db77ab28cb"
}